{% set version = "3.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ecospat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ecospat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ecospat/ecospat_{{ version }}.tar.gz
  sha256: 242c9c1c2df597f343192a6760e1fb7d0e661b2c1249022c66f22c15d59e2f83

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ade4 >=1.6_2
    - r-ape >=3.2
    - r-adehabitathr >=0.4.11
    - r-adehabitatma >=0.3.8
    - r-biomod2 >=4.2_2
    - r-classint >=0.1_23
    - r-dismo >=0.9_3
    - r-ecodist >=1.2.9
    - r-foreach >=1.4.3
    - r-gbm >=2.1.1
    - r-gtools >=3.4.1
    - r-hmisc >=4.4_2
    - r-ks >=1.12.0
    - r-maptools >=0.8_39
    - r-matrixstats >=0.53.1
    - r-nabor >=0.5.0
    - r-poibin >=1.3
    - r-presenceabsence >=1.1.9
    - r-randomforest >=4.6_7
    - r-raster >=2.5_8
    - r-sp >=1.0_15
    - r-vegan >=2.4_1
  run:
    - r-base
    - r-ade4 >=1.6_2
    - r-ape >=3.2
    - r-adehabitathr >=0.4.11
    - r-adehabitatma >=0.3.8
    - r-biomod2 >=4.2_2
    - r-classint >=0.1_23
    - r-dismo >=0.9_3
    - r-ecodist >=1.2.9
    - r-foreach >=1.4.3
    - r-gbm >=2.1.1
    - r-gtools >=3.4.1
    - r-hmisc >=4.4_2
    - r-ks >=1.12.0
    - r-maptools >=0.8_39
    - r-matrixstats >=0.53.1
    - r-nabor >=0.5.0
    - r-poibin >=1.3
    - r-presenceabsence >=1.1.9
    - r-randomforest >=4.6_7
    - r-raster >=2.5_8
    - r-sp >=1.0_15
    - r-vegan >=2.4_1

test:
  commands:
    - $R -e "library('ecospat')"           # [not win]
    - "\"%R%\" -e \"library('ecospat')\""  # [win]

about:
  home: http://www.unil.ch/ecospat/home/menuguid/ecospat-resources/tools.html
  dev_url: https://github.com/ecospat/ecospat
  license: GPL-2.0-or-later
  summary: Collection of R functions and data sets for the support of spatial ecology analyses with a focus on pre, core and post modelling analyses of species distribution, niche quantification and community assembly. Written by current and former members and collaborators of the ecospat group of Antoine Guisan, Department
    of Ecology and Evolution (DEE) and Institute of Earth Surface Dynamics (IDYST), University of Lausanne, Switzerland. Read Di Cola et al. (2016) <doi:10.1111/ecog.02671> for details.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - colineroyaux

# Date/Publication: 2021-02-19 09:10:03 UTC
